@startuml
title CU: Consultar Entregues Disponibles

actor Repartidor

boundary InterficieRepartidor
control GestorRepartidor

entity Entrega

control GestorComanda

entity Comanda

Repartidor -> InterficieRepartidor : seleccionaConsultarEntreguesDisponibles()
InterficieRepartidor -> GestorRepartidor : consultarEntreguesDisponibles()

GestorRepartidor -> Entrega : buscarEntreguesDisponibles()
Entrega --> Comanda : buscarDadesComanda()
Comanda --> Entrega : informacioComanda
Entrega --> GestorRepartidor : llistaEntregues

alt No hi ha entregues disponibles
    GestorRepartidor --> InterficieRepartidor : mostraMissatge("No hi ha entregues disponibles")
else Hi ha entregues disponibles
    GestorRepartidor --> InterficieRepartidor : mostraLlistatEntreguesDisponibles()
end

@enduml