@startuml
title CU: Consultar Dades Entrega

actor Repartidor

boundary InterficieRepartidor
control GestorRepartidor

boundary InterficieComanda
control GestorComanda

entity Entrega
entity Comanda
entity EstatEnviament
entity SeguimentUbicacio

Repartidor -> InterficieRepartidor : seleccionaEntrega(idEntrega)
InterficieRepartidor -> GestorRepartidor : consultarDadesEntrega(idEntrega)

GestorRepartidor -> Entrega : obtenirDadesEntrega(idEntrega)
Entrega --> GestorRepartidor : dadesEntrega

alt L'entrega no es pot consultar
    GestorRepartidor --> InterficieRepartidor : mostraMissatge("No es poden consultar les dades de l'entrega")

else L'entrega es pot consultar
    GestorRepartidor -> EstatEnviament : consultarEstat(idEntrega)
    EstatEnviament --> GestorRepartidor : estatActual

    GestorRepartidor -> SeguimentUbicacio : consultarUbicacio(idEntrega)
    SeguimentUbicacio --> GestorRepartidor : ubicacioActual

    GestorRepartidor -> InterficieComanda : demanarDadesComanda(idComanda)
    InterficieComanda -> GestorComanda : consultarDadesComanda(idComanda)
    GestorComanda -> Comanda : obtenirDadesComanda(idComanda)
    Comanda --> GestorComanda : dadesComanda
    GestorComanda --> InterficieComanda : dadesComanda
    InterficieComanda --> GestorRepartidor : dadesComanda

    GestorRepartidor --> InterficieRepartidor : mostrarDadesEntrega
end

@enduml